### ISSUE TITLE
installer for Arm64

### ISSUE THREAD

**Issue by Pindol83** [LeonStoldt/ghostfolio-installer#9]
Hello, I'm trying to use your script to migrate my postgres12 database to postgres15 in Ghostfolio, but I'm using a system with an arm64 processor. Could you create a special version, or explain how I could create one? I'm not a programmer, so I don't have advanced skills.

thanks

**Comment by LeonStoldt** [comment]
Hi @Pindol83,
Thank you for getting in touch. The current script does not handle the migration of data from an existing running instance. However, I will explore the possibility of providing an arm64-based image for you to use on your server.

If you're interested in upgrading Postgres from version 12 to 15, you can refer to the following post in the Ghostfolio repository: [How to upgrade from PostgreSQL 12 to 15? #2509](https://github.com/ghostfolio/ghostfolio/discussions/2509).
I recommend attempting this migration only if you possess a basic understanding of Docker and databases.

I will notify you once I've an update on the arm64-based image.

**Comment by Pindol83** [comment]
Thanks, I'll take a look tomorrow. Anyway, I think it would be interesting, not only for me, to have an ARM version of your script for migrating from Postgres 12 to Postgres 15.

**Comment by LeonStoldt** [comment]
Hey @Pindol83 ,
I've just introduced an arm64-based image:
```shell
docker pull leonstoldt/ghostfolio-installer:latest_arm64
```
Unfortunately, I couldn't test it on an arm64 system. Please give it a try and share your feedback on whether it works. If successful, I'll consider this issue resolved.

> "interesting [...] to have an ARM version of your script for migrating from Postgres 12 to Postgres 15 (without data)."

You should be able to launch a new ghostfolio with Postgres 15 (empty) using the arm image and migrate the data via the discussion thread mentioned earlier (utilizing pgdump).
